import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

const metadata: Metadata = {
  title: 'Obtenez 10€ sur votre première commande Frichti Market',
  description: 'Generated by create next app'
}

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col min-h-screen`}>
        <header
          className="text-center p-4 bg-gray-100"
          aria-hidden="true"
          role="presentation"
        >
          <p aria-hidden="true" className="text-center max-w-2xl mx-auto">
            Ce site Web n&apos;est pas affilié à La Belle Vie.
          </p>
        </header>
        <main className="flex-1 flex flex-col">{children}</main>
        <footer className="p-4 bg-gray-100">
          <p className="text-center max-w-2xl mx-auto">
            Remise gratuite uniquement valable avec le lien ci-dessus. Code
            promo Frichti Market. Le logo et la copie de Gorillas sont protégés
            par les droits d&apos;auteur de New Frichti SAS. Ce site Web
            n&apos;est pas affilié à New Frichti SAS.
          </p>
        </footer>
      </body>
    </html>
  )
}

export { metadata }

export default RootLayout
